M48
; DRILL file {KiCad 7.0.10} date Friday, November 08, 2024 at 05:18:04 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-08T17:18:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X23.11Y-23.625
X23.11Y-71.625
X51.08Y-71.625
X51.11Y-23.625
M30
